<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Project;

class DummyProjectSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $projects = [
            [
                'project_code' => 'RES-2026-001',
                'name' => 'Azure Heights Residency',
                'client_name' => 'Aaryan Malhotra',
                'client_phone' => '+91 98765 43210',
                'client_email' => 'aaryan@malhotragroup.com',
                'contractor_name' => 'Signature Constructions',
                'project_manager' => 'Vikram Singh',
                'architect' => 'Zaha Architects',
                'location' => 'Worli Sea Face, Mumbai',
                'site_address' => 'Plot 42, Worli Sea Face, Near Coast Guard HQ',
                'city' => 'Mumbai',
                'state' => 'Maharashtra',
                'country' => 'India',
                'zip_code' => '400030',
                'gps_coordinates' => '19.0176° N, 72.8130° E',
                'project_type' => 'Ultra Luxury',
                'building_type' => 'Residential',
                'total_area_sqft' => 125000,
                'number_of_floors' => 45,
                'units_count' => 90,
                'construction_type' => 'RCC',
                'start_date' => '2026-01-15',
                'end_date' => '2028-12-30',
                'estimated_duration' => '36 Months',
                'total_budget' => 450000000,
                'est_cost_materials' => 180000000,
                'est_cost_labor' => 90000000,
                'est_cost_equipment' => 45000000,
                'est_cost_miscellaneous' => 15000000,
                'advance_payment' => 50000000,
                'billing_cycle' => 'Milestone-based',
                'status' => 'Ongoing',
                'priority' => 'High',
                'description' => 'A premier ultra-luxury residential skyscraper featuring panoramic Arabian Sea views and sustainable architectural design.',
                'milestone_planning_approval' => '2025-11-20',
                'milestone_foundation_start' => '2026-02-10',
            ],
            [
                'project_code' => 'COM-2026-004',
                'name' => 'Nexus Quantum Park',
                'client_name' => 'TechNova Solutions',
                'client_phone' => '+91 22 4000 5000',
                'client_email' => 'realestate@technova.com',
                'contractor_name' => 'L&T Construction',
                'project_manager' => 'Sanjay Kapoor',
                'architect' => 'Foster + Partners',
                'location' => 'Hitech City, Hyderabad',
                'site_address' => 'Survey No. 12, Phase 2, Hitech City',
                'city' => 'Hyderabad',
                'state' => 'Telangana',
                'country' => 'India',
                'zip_code' => '500081',
                'gps_coordinates' => '17.4483° N, 78.3915° E',
                'project_type' => 'Premium',
                'building_type' => 'Commercial',
                'total_area_sqft' => 450000,
                'number_of_floors' => 12,
                'units_count' => 4,
                'construction_type' => 'Steel',
                'start_date' => '2026-04-01',
                'end_date' => '2027-10-30',
                'estimated_duration' => '18 Months',
                'total_budget' => 850000000,
                'est_cost_materials' => 350000000,
                'est_cost_labor' => 150000000,
                'est_cost_equipment' => 120000000,
                'est_cost_miscellaneous' => 30000000,
                'advance_payment' => 100000000,
                'billing_cycle' => 'Monthly',
                'status' => 'Planned',
                'priority' => 'Urgent',
                'description' => 'A state-of-the-art IT park designed for AI research labs and high-performance computing centers.',
            ],
            [
                'project_code' => 'IND-2026-009',
                'name' => 'Zenith Logistics Hub',
                'client_name' => 'LogiCore India',
                'client_phone' => '+91 80 2000 3000',
                'client_email' => 'ops@logicore.com',
                'contractor_name' => 'BuildFast Infra',
                'project_manager' => 'Rahul Verma',
                'architect' => 'Industrial Design Corp',
                'location' => 'Bhiwandi, Thane',
                'site_address' => 'Warehouse Zone 4, NH-3, Bhiwandi',
                'city' => 'Thane',
                'state' => 'Maharashtra',
                'country' => 'India',
                'zip_code' => '421302',
                'gps_coordinates' => '19.2967° N, 73.0597° E',
                'project_type' => 'Standard',
                'building_type' => 'Industrial',
                'total_area_sqft' => 200000,
                'number_of_floors' => 2,
                'units_count' => 10,
                'construction_type' => 'Prefab',
                'start_date' => '2025-08-10',
                'end_date' => '2026-05-15',
                'estimated_duration' => '9 Months',
                'total_budget' => 120000000,
                'est_cost_materials' => 60000000,
                'est_cost_labor' => 25000000,
                'est_cost_equipment' => 15000000,
                'est_cost_miscellaneous' => 5000000,
                'advance_payment' => 20000000,
                'billing_cycle' => 'Milestone-based',
                'status' => 'Ongoing',
                'priority' => 'Medium',
                'description' => 'Automated sorting and distribution center with heavy-duty prefab structures and solar-ready roofing.',
                'milestone_planning_approval' => '2025-06-15',
                'milestone_foundation_start' => '2025-09-01',
                'milestone_structure_completion' => '2026-01-20',
            ],
            [
                'project_code' => 'INF-2026-012',
                'name' => 'Riverfront Promenade',
                'client_name' => 'Smart City Mission',
                'client_phone' => '079 2321 0000',
                'client_email' => 'contact@smartcity.gov',
                'contractor_name' => 'Civic Infra Ltd',
                'project_manager' => 'Meera Nair',
                'architect' => 'Urban Scapes',
                'location' => 'Sabarmati Riverfront, Ahmedabad',
                'site_address' => 'Phase 3, Sabarmati Riverfront Development',
                'city' => 'Ahmedabad',
                'state' => 'Gujarat',
                'country' => 'India',
                'zip_code' => '380001',
                'gps_coordinates' => '23.0225° N, 72.5714° E',
                'project_type' => 'Basic',
                'building_type' => 'Infrastructure',
                'total_area_sqft' => 0,
                'number_of_floors' => 0,
                'units_count' => 0,
                'construction_type' => 'Other',
                'start_date' => '2024-01-01',
                'end_date' => '2025-12-31',
                'estimated_duration' => '24 Months',
                'total_budget' => 250000000,
                'est_cost_materials' => 110000000,
                'est_cost_labor' => 80000000,
                'est_cost_equipment' => 40000000,
                'est_cost_miscellaneous' => 10000000,
                'advance_payment' => 0,
                'billing_cycle' => 'Monthly',
                'status' => 'Completed',
                'priority' => 'Low',
                'description' => 'Public infrastructure development including walking tracks, landscaping, and water management systems along the riverfront.',
                'milestone_planning_approval' => '2023-10-10',
                'milestone_foundation_start' => '2024-02-15',
                'milestone_structure_completion' => '2025-06-30',
                'milestone_finishing_phase' => '2025-11-01',
                'milestone_handover' => '2025-12-31',
            ],
        ];

        foreach ($projects as $projectData) {
            Project::updateOrCreate(['project_code' => $projectData['project_code']], $projectData);
        }
    }
}
