<?php

namespace Database\Seeders;

use App\Models\WebsiteContent;
use Illuminate\Database\Seeder;

class WebsiteContentSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $contents = [
            // Header
            [
                'group' => 'header',
                'key' => 'site_name',
                'value' => 'Atom Forge',
                'type' => 'text',
                'label' => 'Site Name',
            ],
            [
                'group' => 'header',
                'key' => 'header_logo_url',
                'value' => '',
                'type' => 'text',
                'label' => 'Logo URL (Optional)',
            ],
            [
                'group' => 'header',
                'key' => 'header_logo_height',
                'value' => '40',
                'type' => 'number',
                'label' => 'Logo Height (px)',
            ],
            [
                'group' => 'header',
                'key' => 'topbar_address',
                'value' => 'HIG II, Gautam Vihar Vistar, Taramandal, Gorakhpur, Uttar Pradesh 273014',
                'type' => 'text',
                'label' => 'Top Bar Address',
            ],
            [
                'group' => 'header',
                'key' => 'topbar_phone',
                'value' => '+91 8318754257',
                'type' => 'text',
                'label' => 'Top Bar Phone',
            ],
            [
                'group' => 'header',
                'key' => 'header_facebook',
                'value' => '#',
                'type' => 'text',
                'label' => 'Header Facebook URL',
            ],
            [
                'group' => 'header',
                'key' => 'header_twitter',
                'value' => '#',
                'type' => 'text',
                'label' => 'Header Twitter URL',
            ],
            [
                'group' => 'header',
                'key' => 'header_linkedin',
                'value' => '#',
                'type' => 'text',
                'label' => 'Header LinkedIn URL',
            ],
            [
                'group' => 'header',
                'key' => 'header_cta_text',
                'value' => 'Request Quote',
                'type' => 'text',
                'label' => 'Header CTA Button Text',
            ],
            [
                'group' => 'header',
                'key' => 'header_cta_link',
                'value' => '/contact',
                'type' => 'text',
                'label' => 'Header CTA Button Link',
            ],

            // Footer
            [
                'group' => 'footer',
                'key' => 'footer_description',
                'value' => "Excellence in construction and architectural design. We build tomorrow's infrastructure with today's precision.",
                'type' => 'textarea',
                'label' => 'Footer Description',
            ],
            [
                'group' => 'footer',
                'key' => 'copyright_text',
                'value' => '© Atom Forge Construction. All rights reserved.',
                'type' => 'text',
                'label' => 'Copyright Text',
            ],
            [
                'group' => 'footer',
                'key' => 'social_facebook',
                'value' => '#',
                'type' => 'text',
                'label' => 'Facebook URL',
            ],
            [
                'group' => 'footer',
                'key' => 'social_twitter',
                'value' => '#',
                'type' => 'text',
                'label' => 'Twitter URL',
            ],
            [
                'group' => 'footer',
                'key' => 'social_linkedin',
                'value' => '#',
                'type' => 'text',
                'label' => 'LinkedIn URL',
            ],

            // Home Page - Hero Slider
            [
                'group' => 'home',
                'key' => 'hero_slide_1_subtitle',
                'value' => 'PRECISE CREATED ONLY FOR YOU',
                'type' => 'text',
                'label' => 'Slide 1 Subtitle',
            ],
            [
                'group' => 'home',
                'key' => 'hero_slide_1_title_dark',
                'value' => 'Building',
                'type' => 'text',
                'label' => 'Slide 1 Title (White)',
            ],
            [
                'group' => 'home',
                'key' => 'hero_slide_1_title_orange',
                'value' => 'Strength',
                'type' => 'text',
                'label' => 'Slide 1 Title (Orange)',
            ],
            [
                'group' => 'home',
                'key' => 'hero_slide_1_description',
                'value' => 'We deliver reliable, innovative, and high-quality construction solutions designed to stand the test of time.',
                'type' => 'textarea',
                'label' => 'Slide 1 Description',
            ],
            [
                'group' => 'home',
                'key' => 'hero_slide_1_image',
                'value' => 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&q=80&w=1920',
                'type' => 'image',
                'label' => 'Slide 1 Image',
            ],
            [
                'group' => 'home',
                'key' => 'hero_slide_2_subtitle',
                'value' => 'PRECISE CREATED ONLY FOR YOU',
                'type' => 'text',
                'label' => 'Slide 2 Subtitle',
            ],
            [
                'group' => 'home',
                'key' => 'hero_slide_2_title_dark',
                'value' => 'Shaping',
                'type' => 'text',
                'label' => 'Slide 2 Title (White)',
            ],
            [
                'group' => 'home',
                'key' => 'hero_slide_2_title_orange',
                'value' => 'The Future',
                'type' => 'text',
                'label' => 'Slide 2 Title (Orange)',
            ],
            [
                'group' => 'home',
                'key' => 'hero_slide_2_description',
                'value' => "At Atom Forge Construction, we don't just build structures—we engineer the future with precision and passion.",
                'type' => 'textarea',
                'label' => 'Slide 2 Description',
            ],
            [
                'group' => 'home',
                'key' => 'hero_slide_2_image',
                'value' => 'https://images.unsplash.com/photo-1503387762-592deb58ef4e?auto=format&fit=crop&q=80&w=1920',
                'type' => 'image',
                'label' => 'Slide 2 Image',
            ],
            [
                'group' => 'home',
                'key' => 'hero_slide_3_subtitle',
                'value' => 'PRECISE CREATED ONLY FOR YOU',
                'type' => 'text',
                'label' => 'Slide 3 Subtitle',
            ],
            [
                'group' => 'home',
                'key' => 'hero_slide_3_title_dark',
                'value' => 'Modern',
                'type' => 'text',
                'label' => 'Slide 3 Title (White)',
            ],
            [
                'group' => 'home',
                'key' => 'hero_slide_3_title_orange',
                'value' => 'Engineering',
                'type' => 'text',
                'label' => 'Slide 3 Title (Orange)',
            ],
            [
                'group' => 'home',
                'key' => 'hero_slide_3_description',
                'value' => 'Combining cutting-edge technology with precision craftsmanship for superior building solutions.',
                'type' => 'textarea',
                'label' => 'Slide 3 Description',
            ],
            [
                'group' => 'home',
                'key' => 'hero_slide_3_image',
                'value' => 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&q=80&w=1920',
                'type' => 'image',
                'label' => 'Slide 3 Image',
            ],

            // Home Page - Stats
            [
                'group' => 'statistics',
                'key' => 'stat_1_value',
                'value' => '10',
                'type' => 'text',
                'label' => 'Stat 1 Value',
            ],
            [
                'group' => 'statistics',
                'key' => 'stat_1_label',
                'value' => 'Winning Awards',
                'type' => 'text',
                'label' => 'Stat 1 Label',
            ],
            [
                'group' => 'statistics',
                'key' => 'stat_2_value',
                'value' => '1230',
                'type' => 'text',
                'label' => 'Stat 2 Value',
            ],
            [
                'group' => 'statistics',
                'key' => 'stat_2_label',
                'value' => 'Satisfied Clients',
                'type' => 'text',
                'label' => 'Stat 2 Label',
            ],
            [
                'group' => 'statistics',
                'key' => 'stat_3_value',
                'value' => '360',
                'type' => 'text',
                'label' => 'Stat 3 Value',
            ],
            [
                'group' => 'statistics',
                'key' => 'stat_3_label',
                'value' => 'Best Projects',
                'type' => 'text',
                'label' => 'Stat 3 Label',
            ],
            [
                'group' => 'statistics',
                'key' => 'stat_4_value',
                'value' => '15+',
                'type' => 'text',
                'label' => 'Stat 4 Value',
            ],
            [
                'group' => 'statistics',
                'key' => 'stat_4_label',
                'value' => 'Years Served',
                'type' => 'text',
                'label' => 'Stat 4 Label',
            ],

            // Home Page - Best Services Section
            [
                'group' => 'home',
                'key' => 'services_section_tagline',
                'value' => 'THE BEST SERVICES',
                'type' => 'text',
                'label' => 'Services Section Tagline',
            ],
            [
                'group' => 'home',
                'key' => 'services_section_title',
                'value' => 'Innovative Building Solutions',
                'type' => 'text',
                'label' => 'Services Section Title',
            ],
            [
                'group' => 'home',
                'key' => 'services_section_subtitle',
                'value' => 'We combine modern engineering, precision craftsmanship, and reliable project management to turn ideas into solid structures, from residential projects to large-scale commercial developments.',
                'type' => 'textarea',
                'label' => 'Services Section Subtitle',
            ],

            // Home Page - Case Studies Section
            [
                'group' => 'home',
                'key' => 'projects_section_tagline',
                'value' => 'CASE STUDIES',
                'type' => 'text',
                'label' => 'Projects Section Tagline',
            ],
            [
                'group' => 'home',
                'key' => 'projects_section_title',
                'value' => 'Latest Projects',
                'type' => 'text',
                'label' => 'Projects Section Title',
            ],

            // Home Page - Video Section
            [
                'group' => 'home',
                'key' => 'video_section_title',
                'value' => 'Our Video Presentation',
                'type' => 'text',
                'label' => 'Video Section Title',
            ],
            [
                'group' => 'home',
                'key' => 'video_section_subtitle',
                'value' => 'Experience our commitment to excellence and innovation through our detailed project showcases and behind-the-scenes look at our construction process.',
                'type' => 'textarea',
                'label' => 'Video Section Subtitle',
            ],
            [
                'group' => 'home',
                'key' => 'video_section_url',
                'value' => 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
                'type' => 'text',
                'label' => 'Video URL',
            ],
            [
                'group' => 'home',
                'key' => 'video_section_bg_image',
                'value' => 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?auto=format&fit=crop&q=80&w=1920',
                'type' => 'image',
                'label' => 'Video Section Background Image',
            ],

            // Home Page - Why Choose Us
            [
                'group' => 'home',
                'key' => 'why_choose_tagline',
                'value' => 'Values',
                'type' => 'text',
                'label' => 'Why Choose Tagline',
            ],
            [
                'group' => 'home',
                'key' => 'why_choose_title',
                'value' => 'Why Choose Atom Forge?',
                'type' => 'text',
                'label' => 'Why Choose Title',
            ],
            [
                'group' => 'home',
                'key' => 'why_choose_subtitle',
                'value' => 'At Atom Forge Construction, we don’t just build structures—we engineer the future. Leveraging cutting-edge technology, smart planning, and efficient execution, we deliver solutions that are built to last.',
                'type' => 'textarea',
                'label' => 'Why Choose Subtitle',
            ],

            // Services Page
            [
                'group' => 'services',
                'key' => 'services_hero_title',
                'value' => 'Our Services',
                'type' => 'text',
                'label' => 'Services Hero Title',
            ],
            [
                'group' => 'services',
                'key' => 'services_hero_subtitle',
                'value' => 'Atom Forge Construction delivers end-to-end building solutions with unmatched quality, speed, and precision from concept to completion.',
                'type' => 'textarea',
                'label' => 'Services Hero Subtitle',
            ],
            [
                'group' => 'services',
                'key' => 'services_cta_title',
                'value' => 'Need a Custom Solution?',
                'type' => 'text',
                'label' => 'Services CTA Title',
            ],
            [
                'group' => 'services',
                'key' => 'services_cta_subtitle',
                'value' => 'We provide tailored services that fit your specific project requirements. Our experts are ready to discuss your ideas.',
                'type' => 'textarea',
                'label' => 'Services CTA Subtitle',
            ],

            // Projects Page
            [
                'group' => 'projects',
                'key' => 'projects_hero_title',
                'value' => 'Built Excellence',
                'type' => 'text',
                'label' => 'Projects Hero Title',
            ],
            [
                'group' => 'projects',
                'key' => 'projects_hero_subtitle',
                'value' => 'Showcasing our journey of building landmarks and transforming spaces with precision engineering.',
                'type' => 'textarea',
                'label' => 'Projects Hero Subtitle',
            ],
            [
                'group' => 'projects',
                'key' => 'project_1_name',
                'value' => 'Skyline Towers',
                'type' => 'text',
                'label' => 'Project 1 Name',
            ],
            [
                'group' => 'projects',
                'key' => 'project_1_type',
                'value' => 'Commercial',
                'type' => 'text',
                'label' => 'Project 1 Type',
            ],
            [
                'group' => 'projects',
                'key' => 'project_1_description',
                'value' => 'A multi-story commercial complex built with modern amenities and energy-efficient designs.',
                'type' => 'textarea',
                'label' => 'Project 1 Description',
            ],
            [
                'group' => 'projects',
                'key' => 'project_1_location',
                'value' => 'City Center, USA',
                'type' => 'text',
                'label' => 'Project 1 Location',
            ],
            [
                'group' => 'projects',
                'key' => 'project_1_image',
                'value' => 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&q=80&w=800',
                'type' => 'image',
                'label' => 'Project 1 Image',
            ],
            [
                'group' => 'projects',
                'key' => 'project_2_name',
                'value' => 'Sunset Villa',
                'type' => 'text',
                'label' => 'Project 2 Name',
            ],
            [
                'group' => 'projects',
                'key' => 'project_2_type',
                'value' => 'Residential',
                'type' => 'text',
                'label' => 'Project 2 Type',
            ],
            [
                'group' => 'projects',
                'key' => 'project_2_description',
                'value' => 'A luxury residential project combining elegant architecture with sustainable living features.',
                'type' => 'textarea',
                'label' => 'Project 2 Description',
            ],
            [
                'group' => 'projects',
                'key' => 'project_2_location',
                'value' => 'South Extension, USA',
                'type' => 'text',
                'label' => 'Project 2 Location',
            ],
            [
                'group' => 'projects',
                'key' => 'project_2_image',
                'value' => 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&q=80&w=800',
                'type' => 'image',
                'label' => 'Project 2 Image',
            ],
            [
                'group' => 'projects',
                'key' => 'project_3_name',
                'value' => 'Greenwood Interiors',
                'type' => 'text',
                'label' => 'Project 3 Name',
            ],
            [
                'group' => 'projects',
                'key' => 'project_3_type',
                'value' => 'Interiors',
                'type' => 'text',
                'label' => 'Project 3 Type',
            ],
            [
                'group' => 'projects',
                'key' => 'project_3_description',
                'value' => 'A full interior design project for a premium workspace, focusing on productivity and comfort.',
                'type' => 'textarea',
                'label' => 'Project 3 Description',
            ],
            [
                'group' => 'projects',
                'key' => 'project_3_location',
                'value' => 'Tech Park, USA',
                'type' => 'text',
                'label' => 'Project 3 Location',
            ],
            [
                'group' => 'projects',
                'key' => 'project_3_image',
                'value' => 'https://images.unsplash.com/photo-1600585154340-be6199f7a09f?auto=format&fit=crop&q=80&w=800',
                'type' => 'image',
                'label' => 'Project 3 Image',
            ],
            [
                'group' => 'projects',
                'key' => 'project_4_name',
                'value' => 'Blue Ridge Apartments',
                'type' => 'text',
                'label' => 'Project 4 Name',
            ],
            [
                'group' => 'projects',
                'key' => 'project_4_type',
                'value' => 'Residential',
                'type' => 'text',
                'label' => 'Project 4 Type',
            ],
            [
                'group' => 'projects',
                'key' => 'project_4_description',
                'value' => 'Modern apartment project with world-class facilities and high-quality construction materials.',
                'type' => 'textarea',
                'label' => 'Project 4 Description',
            ],
            [
                'group' => 'projects',
                'key' => 'project_4_location',
                'value' => 'Outer Ring Road, USA',
                'type' => 'text',
                'label' => 'Project 4 Location',
            ],
            [
                'group' => 'projects',
                'key' => 'project_4_image',
                'value' => 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&q=80&w=800',
                'type' => 'image',
                'label' => 'Project 4 Image',
            ],
            [
                'group' => 'projects',
                'key' => 'project_5_name',
                'value' => 'Industrial Logistics Hub',
                'type' => 'text',
                'label' => 'Project 5 Name',
            ],
            [
                'group' => 'projects',
                'key' => 'project_5_type',
                'value' => 'Commercial',
                'type' => 'text',
                'label' => 'Project 5 Type',
            ],
            [
                'group' => 'projects',
                'key' => 'project_5_description',
                'value' => 'An expansive logistics and manufacturing facility designed for maximum operational efficiency.',
                'type' => 'textarea',
                'label' => 'Project 5 Description',
            ],
            [
                'group' => 'projects',
                'key' => 'project_5_location',
                'value' => 'Industrial Area, USA',
                'type' => 'text',
                'label' => 'Project 5 Location',
            ],
            [
                'group' => 'projects',
                'key' => 'project_5_image',
                'value' => 'https://images.unsplash.com/photo-1503387762-592deb58ef4e?auto=format&fit=crop&q=80&w=800',
                'type' => 'image',
                'label' => 'Project 5 Image',
            ],
            [
                'group' => 'projects',
                'key' => 'project_6_name',
                'value' => 'Zen Workspace',
                'type' => 'text',
                'label' => 'Project 6 Name',
            ],
            [
                'group' => 'projects',
                'key' => 'project_6_type',
                'value' => 'Interiors',
                'type' => 'text',
                'label' => 'Project 6 Type',
            ],
            [
                'group' => 'projects',
                'key' => 'project_6_description',
                'value' => 'Minimalist office interior design project that combines Zen philosophy with modern workplace needs.',
                'type' => 'textarea',
                'label' => 'Project 6 Description',
            ],
            [
                'group' => 'projects',
                'key' => 'project_6_location',
                'value' => 'Hitec City, USA',
                'type' => 'text',
                'label' => 'Project 6 Location',
            ],
            [
                'group' => 'projects',
                'key' => 'project_6_image',
                'value' => 'https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?auto=format&fit=crop&q=80&w=800',
                'type' => 'image',
                'label' => 'Project 6 Image',
            ],

            // About Page
            [
                'group' => 'about',
                'key' => 'about_hero_title',
                'value' => 'About Atom Forge',
                'type' => 'text',
                'label' => 'About Hero Title',
            ],
            [
                'group' => 'about',
                'key' => 'about_hero_subtitle',
                'value' => 'Building the foundations of the future with passion, integrity, and absolute precision.',
                'type' => 'textarea',
                'label' => 'About Hero Subtitle',
            ],
            [
                'group' => 'about',
                'key' => 'about_who_we_are_title',
                'value' => 'Who We Are',
                'type' => 'text',
                'label' => 'Who We Are Title',
            ],
            [
                'group' => 'about',
                'key' => 'about_who_we_are_content',
                'value' => "Atom Forge Construction is a premier firm dedicated to delivering high-quality residential, commercial, and interior projects. We've built a reputation for excellence through our commitment to integrity and innovation.\n\nWe believe every project is a partnership. We work closely with our clients to understand their vision and translate it into reality, ensuring every detail is handled with care and precision.",
                'type' => 'textarea',
                'label' => 'Who We Are Content',
            ],
            [
                'group' => 'about',
                'key' => 'about_who_we_are_image',
                'value' => 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&q=80&w=1200',
                'type' => 'image',
                'label' => 'Who We Are Image',
            ],
            [
                'group' => 'about',
                'key' => 'about_values_title',
                'value' => 'Core Values That Drive Us',
                'type' => 'text',
                'label' => 'Values Section Title',
            ],
            [
                'group' => 'about',
                'key' => 'about_values_subtitle',
                'value' => 'Our foundation is built on principles that ensure we deliver excellence in every square foot we build.',
                'type' => 'textarea',
                'label' => 'Values Section Subtitle',
            ],
            [
                'group' => 'about',
                'key' => 'about_cta_title',
                'value' => 'Work With The Best',
                'type' => 'text',
                'label' => 'About CTA Title',
            ],
            [
                'group' => 'about',
                'key' => 'about_cta_subtitle',
                'value' => 'Join our journey of building excellence. We are always looking for challenging projects that push the boundaries of construction.',
                'type' => 'textarea',
                'label' => 'About CTA Subtitle',
            ],

            // Contact Info
            [
                'group' => 'contact',
                'key' => 'contact_hero_title',
                'value' => "Let's Build Together",
                'type' => 'text',
                'label' => 'Contact Hero Title',
            ],
            [
                'group' => 'contact',
                'key' => 'contact_hero_subtitle',
                'value' => "Have a project in mind? Reach out to us and let's start a conversation about your next big idea.",
                'type' => 'textarea',
                'label' => 'Contact Hero Subtitle',
            ],
            [
                'group' => 'contact',
                'key' => 'contact_info_title',
                'value' => 'Our Information',
                'type' => 'text',
                'label' => 'Contact Info Section Title',
            ],
            [
                'group' => 'contact',
                'key' => 'contact_info_subtitle',
                'value' => 'We are always ready to discuss your projects, answer questions about our services, or provide a detailed quote for your construction needs.',
                'type' => 'textarea',
                'label' => 'Contact Info Section Subtitle',
            ],
            [
                'group' => 'contact',
                'key' => 'contact_phone',
                'value' => '+91 8318754257',
                'type' => 'text',
                'label' => 'Contact Phone',
            ],
            [
                'group' => 'contact',
                'key' => 'contact_whatsapp',
                'value' => '918318754257',
                'type' => 'text',
                'label' => 'WhatsApp Number (without +)',
            ],
            [
                'group' => 'contact',
                'key' => 'contact_email',
                'value' => 'atomforgeconstruction@gmail.com',
                'type' => 'text',
                'label' => 'Contact Email',
            ],
            [
                'group' => 'contact',
                'key' => 'contact_address',
                'value' => 'HIG II, Gautam Vihar Vistar, Taramandal, Gorakhpur, Uttar Pradesh 273014',
                'type' => 'textarea',
                'label' => 'Contact Address',
            ],
            [
                'group' => 'contact',
                'key' => 'contact_form_title',
                'value' => 'Send us a Message',
                'type' => 'text',
                'label' => 'Contact Form Title',
            ],
            [
                'group' => 'contact',
                'key' => 'contact_map_iframe',
                'value' => 'https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d1781.92811524823!2d83.3862029!3d26.7327535!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x399143be04f92235%3A0x5bd0ddd9ec36db2a!2sAtom%20Forge%20Construction!5e0!3m2!1sen!2sin!4v1715326800000!5m2!1sen!2sin',
                'type' => 'textarea',
                'label' => 'Map Iframe URL',
            ],

            // Privacy Policy
            [
                'group' => 'legal',
                'key' => 'privacy_title',
                'value' => 'Privacy Policy',
                'type' => 'text',
                'label' => 'Privacy Policy Title',
            ],
            [
                'group' => 'legal',
                'key' => 'privacy_content',
                'value' => 'Your privacy is important to us. It is Atom Forge Construction\'s policy to respect your privacy regarding any information we may collect from you across our website.',
                'type' => 'textarea',
                'label' => 'Privacy Policy Content',
            ],

            // Terms & Conditions
            [
                'group' => 'legal',
                'key' => 'terms_title',
                'value' => 'Terms and Conditions',
                'type' => 'text',
                'label' => 'Terms and Conditions Title',
            ],
            [
                'group' => 'legal',
                'key' => 'terms_content',
                'value' => 'By accessing this website, you are agreeing to be bound by these website Terms and Conditions of Use, all applicable laws and regulations, and agree that you are responsible for compliance with any applicable local laws.',
                'type' => 'textarea',
                'label' => 'Terms and Conditions Content',
            ],

            // FAQ
            [
                'group' => 'faq',
                'key' => 'faq_title',
                'value' => 'Frequently Asked Questions',
                'type' => 'text',
                'label' => 'FAQ Page Title',
            ],
            [
                'group' => 'faq',
                'key' => 'faq_subtitle',
                'value' => 'Find answers to common questions about our services and processes.',
                'type' => 'textarea',
                'label' => 'FAQ Page Subtitle',
            ],

            // Team Section
            [
                'group' => 'team',
                'key' => 'team_hero_title',
                'value' => 'Meet Our Team',
                'type' => 'text',
                'label' => 'Team Page Hero Title',
            ],
            [
                'group' => 'team',
                'key' => 'team_hero_subtitle',
                'value' => 'Dedicated professionals committed to excellence in every project we undertake.',
                'type' => 'textarea',
                'label' => 'Team Page Hero Subtitle',
            ],
            [
                'group' => 'team',
                'key' => 'team_member_1_name',
                'value' => 'Rajesh Sharma',
                'type' => 'text',
                'label' => 'Member 1 Name',
            ],
            [
                'group' => 'team',
                'key' => 'team_member_1_role',
                'value' => 'Founder & Managing Director',
                'type' => 'text',
                'label' => 'Member 1 Role',
            ],
            [
                'group' => 'team',
                'key' => 'team_member_1_bio',
                'value' => 'Visionary leader with 20+ years of experience in construction and architectural innovation.',
                'type' => 'textarea',
                'label' => 'Member 1 Bio',
            ],
            [
                'group' => 'team',
                'key' => 'team_member_1_image',
                'value' => 'https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&q=80&w=800',
                'type' => 'image',
                'label' => 'Member 1 Image',
            ],

            // Testimonials Section
            [
                'group' => 'testimonials',
                'key' => 'testimonials_tagline',
                'value' => 'Client Success',
                'type' => 'text',
                'label' => 'Testimonials Section Tagline',
            ],
            [
                'group' => 'testimonials',
                'key' => 'testimonials_hero_title',
                'value' => 'What Our Clients Say',
                'type' => 'text',
                'label' => 'Testimonials Hero Title',
            ],
            [
                'group' => 'testimonials',
                'key' => 'testimonials_hero_subtitle',
                'value' => 'We take pride in delivering excellence. Read about the experiences of those who have built their dreams with us.',
                'type' => 'textarea',
                'label' => 'Testimonials Hero Subtitle',
            ],
            [
                'group' => 'testimonials',
                'key' => 'testimonial_1_quote',
                'value' => 'Atom Forge Construction transformed our vision into a stunning reality. Their attention to detail and commitment to quality are truly unmatched in the industry.',
                'type' => 'textarea',
                'label' => 'Testimonial 1 Quote',
            ],
            [
                'group' => 'testimonials',
                'key' => 'testimonial_1_author',
                'value' => 'Arjun Mehta',
                'type' => 'text',
                'label' => 'Testimonial 1 Author',
            ],
            [
                'group' => 'testimonials',
                'key' => 'testimonial_1_location',
                'value' => 'Homeowner, Mumbai',
                'type' => 'text',
                'label' => 'Testimonial 1 Location',
            ],
            [
                'group' => 'testimonials',
                'key' => 'testimonial_1_image',
                'value' => 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=200',
                'type' => 'image',
                'label' => 'Testimonial 1 Image',
            ],
        ];

        foreach ($contents as $content) {
            WebsiteContent::updateOrCreate(['key' => $content['key']], $content);
        }
    }
}
